tabs:
  regional: "RegionalData"
  national: "NationalData"
  subnational: "SubnationalData"
  sources: "Sources"


googlesheets:
  prod: "https://docs.google.com/spreadsheets/d/1FFuz0U5akRhrjg2cQZ7SYZkGLvRmvuSrDCa4SyeU-X0/edit#gid=0"

json:
  filepath: "all.json"

additional_sources:

# national
scraper_national:
  population:
    source: "WorldPop"
    dataset: "worldpop-population-counts-for-ukraine"
    url: "http://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=excel&dataformat=list"
    format: "xls"
    sheet: "Data"
    headers: 3
    prefilter: "Value != ''"
    adm_cols:
      - "Country Code"
    date_col: "Year"
    date_type: "year"
    input_cols:
      - "Value"
    output_cols:
      - "Population"
    output_hxltags:
      - "#population"
  allocations:
    source:
      "#value+cbpf+funding+total+usd": "CBPF"
      "default_source": "CERF"
    source_url:
      "#value+cbpf+funding+total+usd": "https://data.humdata.org/dataset/cbpf-allocations-and-contributions"
      "default_url": "https://data.humdata.org/dataset/cerf-allocations"
    dataset: "cerf-allocations"
    url: "https://cbpfgms.github.io/pfbi-data/download/full_pfmb_allocations.csv"
    format: "csv"
    sort:
      reverse: True
      keys:
        - "AllocationYear"
    date_col: "AllocationYear"
    date_type: "year"
    single_maxdate: True
    adm_cols:
      - "CountryCode"
    filter_cols:
      - "FundType"
    subsets:
      - filter: "FundType == 'CBPF'"
        input_cols:
          - "Budget"
        input_transforms:
          Budget: "float(Budget)"
        sum_cols:
          - formula: "Budget"
        output_cols:
          - "CBPFFunding"
        output_hxltags:
          - "#value+cbpf+funding+total+usd"
      - filter: "FundType == 'CERF'"
        input_cols:
          - "Budget"
        input_transforms:
          Budget: "float(Budget)"
        sum_cols:
          - formula: "Budget"
        output_cols:
          - "CERFFunding"
        output_hxltags:
          - "#value+cerf+funding+total+usd"

fts:
  source: "OCHA"
  url: "https://api.hpc.tools/v"

scraper_subnational:
  population:
    source: "WorldPop"
    dataset: "worldpop-population-counts-for-ukraine"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS3_uBOV_uRDSxOggfBus_pkCs6Iw9lm0nAxzwG14YF_frpm13WPKiM1oNnQ9zrUA/pub?gid=1565793974&single=true&output=csv"
    format: "csv"
    adm_cols:
      - "alpha_3"
      - "ADM1_PCODE"
    input_cols:
      - "POPULATION"
    input_transforms:
      "POPULATION": "get_numeric_if_possible(POPULATION)"
    output_cols:
      - "Population"
    output_hxltags:
      - "#population"

countries:
  - ARE
  - BHR
  - COM
  - DJI
  - DZA
  - EGY
  - IRQ
  - JOR
  - KWT
  - LBN
  - LBY
  - MAR
  - MRT
  - OMN
  - PSE
  - QAT
  - SAU
  - SDN
  - SOM
  - SYR
  - TUN
  - YEM

country_name_overrides:
  PSE: "oPt"

country_name_mappings:

admin1_info:

admin1_name_mappings:

admin1_name_replacements:
  " urban": ""
  "sud": "south"
  "ouest": "west"
  "est": "east"
  "nord": "north"
  "'": ""
  "/": " "
  ".": " "
  " region": ""

admin1_fuzzy_dont:
  - "nord"
  - "north"
  - "sud"
  - "south"
  - "est"
  - "east"
  - "ouest"
  - "west"
